name: CI with Secrets

on:
  push:

jobs:
  ci-job:
    runs-on: ubuntu-latest

    env:
      MESSAGE: ${{ secrets.MY_SECRET_VALUE }}

    steps:
      - name: Print secret safely
        run: echo "Message is $MESSAGE"
